version: 2
updates:

# GitHub actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
  ignore:
  # See: https://github.com/bakunyo/git-pr-release-action/issues/15, https://github.com/samunohito/SimpleVolumeMixer/commit/2059044c71236509466cf9b1bb2d56d515274938
  - dependency-name: bakunyo/git-pr-release-action
  labels:
  - github-actions
  - type/dependencies

# npm
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  versioning-strategy: lockfile-only
  commit-message:
    prefix: ci
    include: scope
  labels:
  - npm
  - type/dependencies

# Docker
- package-ecosystem: docker
  directory: /.devcontainer/
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
  labels:
  - docker
  - type/dependencies
- package-ecosystem: docker
  directory: /docker/
  schedule:
    interval: daily
  commit-message:
    prefix: ci
    include: scope
  labels:
  - docker
  - type/dependencies
