pull_request_rules:
  - name: Automatic merge for Preparing next version
    conditions:
      # [MEMO] Branch protection settings are injected
      - author = github-actions[bot]
      - label = "type/prepare-next-version"
    actions:
      review:
        type: APPROVE
        message: Automatically approving github-actions[bot]
      merge:
        method: merge
  - name: Automatic merge for Dependabot pull requests
    conditions:
      # [MEMO] Branch protection settings are injected
      - author = dependabot[bot]
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot[bot]
      merge:
        method: merge
