name: Application - Benchmark

on:
  push:

jobs:
  benchmark:
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    strategy:
      matrix:
        run-script-name:
        - test:performance:tempfile_mode
        - test:performance:stream_mode
        node-js-heap-size:
        - 200
        - 400
        - 800
        - 1600
      fail-fast: false
    services:
      fake-gcs-server:
        image: fsouza/fake-gcs-server:1.52.1
        ports:
        - 4443:4443
        options: >-
          --health-cmd "wget -q -S -O - --no-check-certificate https://localhost:4443/_internal/healthcheck"
    steps:
    - name: Collect Workflow Telemetry - ${{ matrix.run-script-name }}
      uses: ryu-sato/workflow-telemetry-action@refs/heads/fix/some-problem
      with:
        metric_frequency: 1          # Collection interval (seconds)
        proc_trace_min_duration: 0   # Trace all processes
        comment_on_pr: false         # Output results in PR comments
        job_summary: true            # Output results to Job Summary

    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: "yarn"
    - name: Create bucket "gs://performance-test"
      run: >-
        node -e "
        fetch('https://localhost:4443/storage/v1/b',{
          method:'POST',
          headers:{'Content-Type':'application/json'},
          body:JSON.stringify({
            name:'test-performance'
          })
        })
        .then(r=>console.log(r.text()))
        .catch(console.error)"
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    - run: yarn install
    - run: yarn build --filter "@awesome-database-backup/file-backup"
    - name: Run performance test - ${{ matrix.run-script-name }}
      run: yarn run ${{ matrix.run-script-name }} --filter "@awesome-database-backup/file-backup"
      env:
        GCP_ENDPOINT_URL: https://localhost:4443
        NODE_TLS_REJECT_UNAUTHORIZED: 0
        NODE_OPTIONS: '--max-old-space-size=${{ matrix.node-js-heap-size }}'
