name: Profile backup exec

on:
  push:

jobs:
  profile:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
      with:
        metric_frequency: 5          # Collection interval (seconds)
        proc_trace_min_duration: 0   # Trace all processes
        comment_on_pr: true          # Output results in PR comments
        job_summary: true            # Output results to Job Summary
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: "yarn"
    - run: yarn install
    - name: Run performance test
      run: yarn run test:performance
