name: Application - Benchmark

on:
  push:

jobs:
  benchmark:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    container: node:lts-slim
    services:
      fake-gcs-server:
        image: fsouza/fake-gcs-server:1.52.1
        ports:
          4443:4443
        options: >-
          --health-cmd "wget -q -S -O - --no-check-certificate https://localhost:4443/_internal/healthcheck"
    steps:
    - uses: actions/checkout@v4
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
      with:
        metric_frequency: 5          # Collection interval (seconds)
        proc_trace_min_duration: 0   # Trace all processes
        comment_on_pr: true          # Output results in PR comments
        job_summary: true            # Output results to Job Summary
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: "yarn"
    - run: yarn install
    - name: Configure fake-gcs-server
      run: >-
        curl --insecure -v -X PUT -H "Content-Type: application/json" -d
        '{
          "schema": "http",
          "publicHost": "fake-gcs-server",
          "externalUrl": "http://fake-gcs-server:4443"
        }'
        https://fake-gcs-server:4443/_internal/config
    - name: Run performance test
      run: yarn run test:performance
