name: Misc - Command - Bump up version

on:
  issue_comment:
    types: [created, edited]

jobs:

  misc-command-bump-version:
    runs-on: ubuntu-latest

    if: >
      contains( github.event.comment.html_url, '/pull/' )
      && startsWith( github.event.comment.body, '/bump-version ' )
      && github.head_ref == 'next-version'
    steps:
    - name: Set up range to 'patch'
      if: github.event.comment.body == '/bump-version patch'
      run: echo "UP_RANGE=patch" >> $GITHUB_ENV
    - name: Set up range to 'minor'
      if: github.event.comment.body == '/bump-version minor'
      run: echo "UP_RANGE=minor" >> $GITHUB_ENV
    - name: Set up range to 'major'
      if: github.event.comment.body == '/bump-version major'
      run: echo "UP_RANGE=major" >> $GITHUB_ENV
    - name: Check up range
      if: >
        ! contains(fromJSON('["patch", "minor", "major"]'), env.UP_RANGE)
      run: echo 'invalid up range'; exit 1
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: "yarn"
    - run: yarn install
    - name: Bump up version
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        yarn run "bump-version:${UP_RANGE}"

        git commit -am 'Bump up version'
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
