name: Misc - Pull Request to master branch

on:
  pull_request:
    branches:
    - master
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, edited, synchronize]

jobs:

  # Refs: https://github.com/release-drafter/release-drafter
  labeling:
    runs-on: ubuntu-latest

    if: >
      !contains( github.event.pull_request.labels.*.name, 'exclude from changelog' )

    steps:
    - uses: release-drafter/release-drafter@v5
      with:
        disable-releaser: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-title:
    runs-on: ubuntu-latest

    # Ignore these cases
    # - Out of changelog target
    # - Created by "dependabot", "github-actions"
    if: >
      (
        !contains( github.event.pull_request.labels.*.name, 'exclude from changelog' )
        && !startsWith( github.head_ref, 'dependabot/' )
        && !contains( github.actor, 'github-actions' )
      )
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        with:
          types: |
            feat
            imprv
            fix
            support
            chore
            ci
            docs
            test
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  slack-notification:
    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses:  act10ns/slack@v2.0.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        # "status" is used to be set notification's color.
        # When "status" is "success", "failure", or "canceled", color is green, red, or yellow; otherwise it is #C0C0C0C0.
        # see. https://github.com/act10ns/slack/blob/da3191ebe2e67f49b46880b4633f5591a96d1d33/src/slack.ts#L23
        status: updated
        channel: '#srv'
