name: Release - Update draft

on:
  push:
    branches:
    - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:

  # Refs: https://github.com/release-drafter/release-drafter
  release-update_draft:
    runs-on: ubuntu-latest

    outputs:
      RELEASE_VERSION: ${{ steps.package-json.outputs.full }}
      RELEASE_DRAFT_BODY: ${{ steps.release-drafter.outputs.body }}

    steps:
    - uses: actions/checkout@v5

    - name: Retrieve information from package.json
      uses: xile611/read-package-version-action@v2.1
      id: package-json

    # Drafts your next Release notes as Pull Requests are merged into "master"
    - uses: release-drafter/release-drafter@v6
      id: release-drafter
      with:
        name: v${{ steps.package-json.outputs.full }}
        tag: v${{ steps.package-json.outputs.full }}
        version: ${{ steps.package-json.outputs.full }}
        disable-autolabeler: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Refs: https://github.com/bakunyo/git-pr-release-action
  update-release-pr:
    needs: release-update_draft

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Create/Update Pull Request
      uses: bakunyo/git-pr-release-action@v1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: stable
        GIT_PR_RELEASE_BRANCH_STAGING: master
        GIT_PR_RELEASE_TEMPLATE: .github/git-pr-release-template.erb
        GIT_PR_RELEASE_TITLE: Release v${{ needs.release-update_draft.outputs.RELEASE_VERSION }}
        GIT_PR_RELEASE_BODY: ${{ needs.release-update_draft.outputs.RELEASE_DRAFT_BODY }}
